### ISSUE TITLE
The questions about code in specific places is there are some reason for that (to clarify) and follow your practice

### ISSUE THREAD

**Issue by Oleksii909** [MeetMartin/quotes#1]
https://github.com/MeetMartin/quotes/blob/8b64e9128e2fac873fd5f2fa189bafd4d19d24d4/src/store/StoreContext.js#L4

Why do you exported objects in reducers.js with order  `initialState` and `reducers` but when you require it you put different order?

**Comment by Oleksii909** [comment]
https://github.com/MeetMartin/quotes/blob/8b64e9128e2fac873fd5f2fa189bafd4d19d24d4/src/store/reducers.js#L2
And why is here are used double quote for importing `types` while for other imports used single quotes?

**Comment by MeetMartin** [comment]
the order nor quotes have functional impact. I have simply not noticed. It is also quite likely that one of the cases are caused by IDE auto completion. When you use the code, feel free to unify or you may create a pull request to fix these in the code base here as well.
